# Generated by Django 4.2.7 on 2025-07-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroP', '0002_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
